version: "3.1"
services:
  db-wa:
    image: mongo:4.2
    container_name: db-wa
    # restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
        - net-wa

  api-wa:
    # image: node:10.14.0
    container_name: api-wa
    build: .
    env_file:
     - .env
    depends_on:
      - db-wa
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
        - net-wa
     #============ comment when to push to master branch ===============
    volumes:
      - .:/usr/src/app:rw
    working_dir: /usr/src/app
    #==================================================================
    command: bash -c "npm start" 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  net-wa:
    external:
      name: net-wa
    # driver: "bridge"


volumes:
  mongodbdata:
    driver: local